'use strict';

function renderSettings() {
    const configReady = Boolean(cloudConfig.url && cloudConfig.key), userEmail = cloud.user?.email || '';
    const aiActions = [...state.aiActions].sort((a,b) => String(b.createdAt || '').localeCompare(String(a.createdAt || ''))).slice(0, 6);
    const pendingOps = state.syncQueue.filter(q => !q.lastError).length, failedOps = state.syncQueue.filter(q => q.lastError).length;
    const safetyBackup = getSafetyBackup();
    const advancedOpen = Boolean(cloud.remotePending || failedOps || qaReport?.local?.failures || qaReport?.cloud?.level === 'fail');
    app.innerHTML = `<section class="section flush-top"><div class="section-head"><div><p class="eyebrow">Preferences & data</p><h2>Settings</h2></div><span class="tag success">V${escapeHtml(RELEASE_VERSION)}</span></div><div class="settings-list">
      <form class="setting-card" id="targetsForm"><div class="setting-title"><div><h3>Daily targets</h3><p>Saving updates today's target snapshot and the default used for newly created days. Older logged days keep their original targets.</p></div><span class="tag ${state.profile.targetsConfirmed ? 'success' : 'warn'}">${state.profile.targetsConfirmed ? 'Confirmed' : 'Set up'}</span></div><div class="field-grid"><label>Calories<input id="settingsCalories" type="number" min="500" max="10000" step="10" value="${escapeHtml(state.profile.calorieTarget)}" required/></label><label>Protein (g)<input id="settingsProtein" type="number" min="0" max="1000" step="1" value="${escapeHtml(state.profile.proteinTarget)}" required/></label></div><div class="modal-actions"><span class="spacer"></span><button class="btn primary" type="submit">Save from today</button></div></form>

      <div class="setting-card" id="cloudCard"><div class="setting-title"><div><h3>Cloud sync</h3><p>Optional. Keep devices aligned and enable authenticated ChatGPT database actions.</p></div>${cloudStatusTag()}</div>
        <form id="cloudConfigForm"><label>Supabase project URL<input id="cloudUrl" type="url" placeholder="https://your-project.supabase.co" value="${escapeHtml(cloudConfig.url || '')}" ${configReady ? '' : 'required'}/></label><label>Publishable key<input id="cloudKey" type="password" autocomplete="off" placeholder="sb_publishable_..." value="${escapeHtml(cloudConfig.key || '')}" ${configReady ? '' : 'required'}/></label><div class="hint">Use a publishable/anon client key only. Secret/service-role keys are rejected.</div><div class="inline-actions"><button class="btn ghost" type="submit">${configReady ? 'Reconnect' : 'Save & connect'}</button><button class="btn ghost danger ${configReady ? '' : 'hidden'}" type="button" id="forgetCloudBtn">Forget cloud config</button></div></form>
        ${configReady && !cloud.user ? `<hr/><form id="authForm"><div class="field-grid"><label>Email<input id="authEmail" type="email" autocomplete="email" required/></label><label>Password<input id="authPassword" type="password" autocomplete="current-password" minlength="6" required/></label></div><div class="inline-actions"><button class="btn primary" type="submit">Sign in</button><button class="btn ghost" type="button" id="signUpBtn">Create account</button></div></form>` : ''}
        ${cloud.user ? `<hr/><div class="account-row"><div><strong>${escapeHtml(userEmail)}</strong><small>${cloud.lastSyncAt ? `Last sync ${new Date(cloud.lastSyncAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}` : 'Cloud session active'}</small></div><button class="btn ghost" id="signOutBtn">Sign out</button></div><div class="sync-actions"><button class="btn primary" id="syncNowBtn">Sync now</button><button class="btn ghost" id="uploadCloudBtn">Replace cloud ← this device</button><button class="btn ghost" id="downloadCloudBtn">Replace device ← cloud</button></div>` : ''}
        ${cloud.remotePending ? `<div class="conflict-box"><strong>Cloud changed while this device has unsynced edits.</strong><p>Choose which side wins. Nothing is discarded automatically.</p><div class="inline-actions"><button class="btn primary" id="keepLocalBtn">Keep local edits</button><button class="btn ghost danger" id="useCloudBtn">Use cloud instead</button></div></div>` : `<div class="hint">Realtime refresh applies automatically when there are no pending local edits. Conflicting changes are surfaced instead of silently overwritten.</div>`}
        ${cloud.error && !cloud.remotePending ? `<div class="cloud-error" role="alert"><strong>Cloud sync needs attention</strong><span>${escapeHtml(cloud.error)}</span></div>` : ''}
      </div>

      <div class="setting-card"><div class="setting-title"><div><h3>Install app</h3><p>Diet Copilot works as a lightweight PWA and keeps local tracking available after the app shell has been cached.</p></div><span class="tag">PWA</span></div><div class="inline-actions"><button class="btn ghost" id="installAppBtn">${window.matchMedia?.('(display-mode: standalone)').matches ? 'Installed' : 'Install app'}</button></div></div>

      <div class="setting-card"><h3>Backup</h3><p>Export a portable JSON copy of your local Diet Copilot data. Importing replaces local data and deactivates automatic cloud sync until you choose a sync direction again.</p><div class="inline-actions"><button class="btn ghost" id="exportBtn">Export JSON</button><label class="btn ghost file-btn">Import JSON<input id="importFile" type="file" accept="application/json,.json"/></label>${hasSafetyBackup() ? `<button class="btn ghost" id="restoreSafetyBtn">Restore safety backup</button>` : ''}</div>${safetyBackup ? `<div class="hint">Last safety backup: ${escapeHtml(new Date(safetyBackup.capturedAt).toLocaleString())} · ${escapeHtml(safetyBackup.reason || 'automatic')}</div>` : ''}</div>

      <details class="advanced-settings" ${advancedOpen ? 'open' : ''}><summary><div><strong>Advanced & diagnostics</strong><small>Health checks, ChatGPT bridge, rollback and troubleshooting</small></div><span aria-hidden="true">⌄</span></summary><div class="advanced-settings-body">
        <div class="setting-card release-card"><div class="setting-title"><div><h3>Health check</h3><p>Validates local records, queue consistency, browser storage and—when cloud sync is active—the Supabase schema.</p></div><span class="tag">System</span></div>${releaseCheckMarkup()}<div class="inline-actions release-actions"><button class="btn primary" id="runReleaseCheckBtn">Run health check</button><button class="btn ghost" id="repairLocalBtn">Repair safe local issues</button></div></div>

        <div class="setting-card"><div class="setting-title"><div><h3>ChatGPT bridge</h3><p>Provides compact diet context plus idempotent create, correction, deletion, weight and undo RPCs when the cloud schema is installed.</p></div><span class="tag ${cloud.user && cloudConfig.activated ? 'success' : ''}">${cloud.user && cloudConfig.activated ? 'Ready' : 'Local preview'}</span></div><div class="inline-actions"><button class="btn primary" id="copyAiContextBtn">Copy 14-day AI context</button>${cloud.user && cloudConfig.activated ? `<button class="btn ghost" id="refreshAiBtn">Refresh AI activity</button>` : ''}</div><div class="hint">Cloud mode uses <code>get_diet_context(...)</code>; local mode builds the same shape from browser data.</div>${aiActions.length ? `<div class="ai-activity">${aiActions.map(renderAiAction).join('')}</div>` : `<div class="empty mini-empty"><strong>No AI mutations yet</strong>Actions performed through the authenticated RPC bridge appear here with an undo trail.</div>`}</div>

        <div class="setting-card"><h3>Recovery & diagnostics</h3><div class="diagnostics"><span>Release <strong>V${escapeHtml(RELEASE_VERSION)}</strong></span><span>State schema <strong>v${STATE_VERSION}</strong></span><span>Meals <strong>${state.meals.length}</strong></span><span>Meal items <strong>${state.meals.reduce((a, m) => a + (m.items?.length || 0), 0)}</strong></span><span>Saved foods <strong>${state.savedFoods.length}</strong></span><span>Saved meals <strong>${state.savedMeals.length}</strong></span><span>Pending sync <strong>${pendingOps}</strong></span><span>Failed sync <strong>${failedOps}</strong></span><span>AI actions <strong>${state.aiActions.length}</strong></span><span>Weights <strong>${state.weights.length}</strong></span><span>Network <strong>${isOnline() ? 'Online' : 'Offline'}</strong></span></div><div class="inline-actions"><button class="btn ghost" id="copyDebugBtn">Copy diagnostic summary</button>${failedOps ? `<button class="btn ghost" id="retryFailedBtn">Retry failed sync</button>` : ''}${hasMigrationBackup() ? `<button class="btn ghost" id="restoreMigrationBtn">Restore pre-V1 migration backup</button>` : ''}<button class="btn ghost danger" id="resetBtn">Reset local data</button></div></div>
      </div></details>
    </div></section>`;
    bindSettings();
  }


