'use strict';
  function renderSettings() {
    const configReady = Boolean(cloudConfig.url && cloudConfig.key), userEmail = cloud.user?.email || '';
    const aiActions = [...state.aiActions].sort((a,b) => String(b.createdAt || '').localeCompare(String(a.createdAt || ''))).slice(0, 6);
    const pendingOps = state.syncQueue.filter(q => !q.lastError).length, failedOps = state.syncQueue.filter(q => q.lastError).length;
    app.innerHTML = `<section class="section flush-top"><div class="section-head"><div><p class="eyebrow">Release candidate controls</p><h2>Settings</h2></div></div><div class="settings-list">
      <div class="setting-card release-card"><div class="setting-title"><div><h3>V0.5 release check</h3><p>Validates local records, queue consistency, browser storage and—when enabled—the live Supabase schema before V1.</p></div><span class="tag">RC</span></div>${releaseCheckMarkup()}<div class="inline-actions release-actions"><button class="btn primary" id="runReleaseCheckBtn">Run release check</button><button class="btn ghost" id="repairLocalBtn">Repair safe local issues</button></div></div>
      <form class="setting-card" id="targetsForm"><div class="setting-title"><div><h3>Daily targets</h3><p>Saving updates today's target snapshot and the default used for newly created days. Older logged days keep their original targets.</p></div><span class="tag">Date-aware</span></div><div class="field-grid"><label>Calories<input id="settingsCalories" type="number" min="500" max="10000" step="10" value="${escapeHtml(state.profile.calorieTarget)}" required/></label><label>Protein (g)<input id="settingsProtein" type="number" min="0" max="1000" step="1" value="${escapeHtml(state.profile.proteinTarget)}" required/></label></div><div class="modal-actions"><span class="spacer"></span><button class="btn primary" type="submit">Save from today</button></div></form>

      <div class="setting-card" id="cloudCard"><div class="setting-title"><div><h3>Supabase cloud</h3><p>Optional. V0.5 adds safer multi-device handling and an authenticated AI action surface.</p></div>${cloudStatusTag()}</div>
        <form id="cloudConfigForm"><label>Project URL<input id="cloudUrl" type="url" placeholder="https://your-project.supabase.co" value="${escapeHtml(cloudConfig.url || '')}"/></label><label>Publishable key<input id="cloudKey" type="password" autocomplete="off" placeholder="sb_publishable_..." value="${escapeHtml(cloudConfig.key || '')}"/></label><div class="hint">Use a publishable/anon client key only. Never paste a service-role or secret key into a browser app.</div><div class="inline-actions"><button class="btn ghost" type="submit">${configReady ? 'Reconnect' : 'Save & connect'}</button><button class="btn ghost danger ${configReady ? '' : 'hidden'}" type="button" id="forgetCloudBtn">Forget cloud config</button></div></form>
        ${configReady && !cloud.user ? `<hr/><form id="authForm"><div class="field-grid"><label>Email<input id="authEmail" type="email" autocomplete="email" required/></label><label>Password<input id="authPassword" type="password" autocomplete="current-password" minlength="6" required/></label></div><div class="inline-actions"><button class="btn primary" type="submit">Sign in</button><button class="btn ghost" type="button" id="signUpBtn">Create account</button></div></form>` : ''}
        ${cloud.user ? `<hr/><div class="account-row"><div><strong>${escapeHtml(userEmail)}</strong><small>${cloud.lastSyncAt ? `Last sync ${new Date(cloud.lastSyncAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}` : 'Cloud session active'}</small></div><button class="btn ghost" id="signOutBtn">Sign out</button></div><div class="sync-actions"><button class="btn primary" id="syncNowBtn">Sync now</button><button class="btn ghost" id="uploadCloudBtn">Replace cloud ← this device</button><button class="btn ghost" id="downloadCloudBtn">Replace device ← cloud</button></div>` : ''}
        ${cloud.remotePending ? `<div class="conflict-box"><strong>Cloud changed while this device has unsynced edits.</strong><p>Choose which side wins. Nothing is discarded automatically.</p><div class="inline-actions"><button class="btn primary" id="keepLocalBtn">Keep local edits (local wins)</button><button class="btn ghost danger" id="useCloudBtn">Discard local edits + use cloud</button></div></div>` : `<div class="hint">Realtime refresh applies automatically only when there are no pending local edits. Concurrent changes are surfaced instead of silently overwriting your work.</div>`}
      </div>

      <div class="setting-card"><div class="setting-title"><div><h3>ChatGPT bridge</h3><p>V0.5 can expose a compact read context plus idempotent meal/weight create, correction, deletion and undo RPCs after the V0.5 schema is installed.</p></div><span class="tag ${cloud.user && cloudConfig.activated ? 'success' : ''}">${cloud.user && cloudConfig.activated ? 'Ready' : 'Local preview'}</span></div><div class="inline-actions"><button class="btn primary" id="copyAiContextBtn">Copy 14-day AI context</button>${cloud.user && cloudConfig.activated ? `<button class="btn ghost" id="refreshAiBtn">Refresh AI activity</button>` : ''}</div><div class="hint">The copied context is also useful for debugging. Cloud mode uses <code>get_diet_context(...)</code>; local mode builds the same shape from browser data.</div>${aiActions.length ? `<div class="ai-activity">${aiActions.map(renderAiAction).join('')}</div>` : `<div class="empty mini-empty"><strong>No AI mutations yet</strong>Actions performed through the V0.5 RPC bridge will appear here with an undo trail.</div>`}</div>

      <div class="setting-card"><div class="setting-title"><div><h3>Install / offline shell</h3><p>The V0.5 project includes a manifest and service worker so GitHub Pages can behave like an installable lightweight app after first load.</p></div><span class="tag">PWA</span></div><div class="inline-actions"><button class="btn ghost" id="installAppBtn">${window.matchMedia?.('(display-mode: standalone)').matches ? 'Installed' : 'Install app'}</button></div></div>

      <div class="setting-card"><h3>Backup & rollback</h3><p>JSON backup includes item-level meals, uncertainty ranges, reusable foods and local sync metadata. V0.5 also captures a one-time pre-migration snapshot when upgrading from an older local version.</p><div class="inline-actions"><button class="btn ghost" id="exportBtn">Export JSON</button><label class="btn ghost file-btn">Import JSON<input id="importFile" type="file" accept="application/json,.json"/></label>${hasMigrationBackup() ? `<button class="btn ghost" id="restoreMigrationBtn">Restore pre-V0.5 backup</button>` : ''}</div></div>

      <div class="setting-card"><h3>Diagnostics</h3><div class="diagnostics"><span>Meals <strong>${state.meals.length}</strong></span><span>Meal items <strong>${state.meals.reduce((a, m) => a + (m.items?.length || 0), 0)}</strong></span><span>Saved foods <strong>${state.savedFoods.length}</strong></span><span>Saved meals <strong>${state.savedMeals.length}</strong></span><span>Pending sync <strong>${pendingOps}</strong></span><span>Failed sync <strong>${failedOps}</strong></span><span>Cloud baselines <strong>${Object.keys(state.cloudBaselines || {}).length}</strong></span><span>AI actions <strong>${state.aiActions.length}</strong></span><span>Weights <strong>${state.weights.length}</strong></span><span>Network <strong>${isOnline() ? 'Online' : 'Offline'}</strong></span></div><div class="inline-actions"><button class="btn ghost" id="copyDebugBtn">Copy summary</button>${failedOps ? `<button class="btn ghost" id="retryFailedBtn">Retry failed sync</button>` : ''}<button class="btn ghost danger" id="resetBtn">Reset local data</button></div></div>
    </div></section>`;
    bindSettings();
  }
