import fs from 'node:fs';

const release='1.0-rc1';
const jsSources=[
  'dashboard-01.js',
  'dashboard-02.js',
  'dashboard-p2.js',
  'dashboard-p2-session.js',
  'dashboard-p3.js',
  'dashboard-03.js',
  'dashboard-auth-persist.js',
  'dashboard-auth.js',
  'dashboard-p4.js',
  'dashboard-p5.js',
  'dashboard-p6.js',
  'dashboard-v5.js',
  'dashboard-v5-2.js',
  'dashboard-v5-3.js',
  'dashboard-auth-final.js',
  'dashboard-04.js',
  'dashboard-v6-2.js',
  'dashboard-v6-3.js',
  'dashboard-v6-4.js',
  'dashboard-v6-5.js',
  'dashboard-v6-6.js',
  'dashboard-v6-7.js',
  'dashboard-ops.js'
];

const cssSources=[
  'dashboard-01.css',
  'dashboard-02.css',
  'dashboard-03.css',
  'dashboard-p2.css',
  'dashboard-p3.css',
  'dashboard-p4.css',
  'dashboard-p5.css',
  'dashboard-p6.css',
  'dashboard-v5.css',
  'dashboard-v5-2.css',
  'dashboard-v5-3.css',
  'dashboard-v6-2.css',
  'dashboard-v6-6.css',
  'dashboard-v6-7.css'
];

const obsoleteRuntime=[
  'dashboard-v5-1.js',
  'dashboard-v6.js',
  'dashboard-v6-1.js',
  'dashboard-v6-1-2.js'
];
const obsoleteStyles=[
  'dashboard-v5-1.css',
  'dashboard-v6.css',
  'dashboard-v6-1-1.css',
  'dashboard-v6-3.css',
  'dashboard-v6-5.css'
];

for(const file of [...jsSources,...cssSources]){
  if(!fs.existsSync(file))throw new Error(`Missing V6.7 source: ${file}`);
}
for(const file of obsoleteRuntime){
  if(jsSources.includes(file))throw new Error(`Obsolete runtime fragment returned to production: ${file}`);
}
for(const file of obsoleteStyles){
  if(cssSources.includes(file))throw new Error(`Obsolete style fragment returned to production: ${file}`);
}

let js=`/* Diet Copilot Web V1.0 RC1 — generated by scripts/build-v67.mjs.\n   Production bundle; source fragments remain in the repository for audit history. */\n`;
for(const file of jsSources){
  js+=`\n/* ===== ${file} ===== */\n${fs.readFileSync(file,'utf8').trim()}\n`;
}
js=js.replace("const RELEASE = '3.2';",`const RELEASE = '${release}';`);

if(js.includes('function v6CaptureMarkup'))throw new Error('Quick Capture implementation leaked into production bundle.');
if(js.includes('data-v6-capture="'))throw new Error('Quick Capture controls leaked into production bundle.');
if(js.includes('data-v6-recipe-log="'))throw new Error('Legacy recipe logging controls leaked into production bundle.');
if(!js.includes('renderInsightsV66'))throw new Error('Consolidated Insights renderer missing.');
if(!js.includes('renderTodayV67'))throw new Error('V6.7 Today invariant missing.');
if(!js.includes('Logged nutrition always counts'))throw new Error('All-logged-data policy missing from bundle.');
fs.writeFileSync('diet-app.js',js);

let css=`/* Diet Copilot Web V1.0 RC1 — consolidated production stylesheet. */\n`;
for(const file of cssSources){
  css+=`\n/* ===== ${file} ===== */\n${fs.readFileSync(file,'utf8').trim()}\n`;
}
fs.writeFileSync('diet.css',css);

let html=fs.readFileSync('index.html','utf8');
html=html.replace(/^\s*<link rel="stylesheet" href="(?:dashboard-[^"]+|diet\.css[^"]*)" \/>\s*$/gm,'');
html=html.replace(/^\s*<script src="(?:dashboard-[^"]+|diet-app\.js[^"]*)"><\/script>\s*$/gm,'');
html=html.replace('</head>',`  <link rel="stylesheet" href="diet.css?v=${release}" />\n</head>`);
html=html.replace('</body>',`  <script src="diet-app.js?v=${release}"></script>\n</body>`);
fs.writeFileSync('index.html',html);

const sw=`const CACHE='diet-copilot-web-v1-rc1';\nconst CORE=['./','./index.html','./diet.css?v=${release}','./diet-app.js?v=${release}','./.well-known/thiepn-app.json','./manifest.webmanifest','./icon.svg','./icon-192.png','./icon-512.png'];\nself.addEventListener('install',e=>e.waitUntil(caches.open(CACHE).then(c=>c.addAll(CORE)).then(()=>self.skipWaiting())));\nself.addEventListener('activate',e=>e.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==CACHE&&k.startsWith('diet-copilot')).map(k=>caches.delete(k)))).then(()=>self.clients.claim())));\nfunction fresh(r){try{return new Request(r,{cache:'no-cache'})}catch{return r}}\nfunction networkFirst(r,fallback=r){return fetch(fresh(r)).then(res=>{if(res?.ok)caches.open(CACHE).then(c=>c.put(fallback,res.clone()));return res}).catch(()=>caches.match(fallback))}\nself.addEventListener('fetch',e=>{const r=e.request;if(r.method!=='GET')return;const u=new URL(r.url);if(u.origin!==self.location.origin)return;if(r.mode==='navigate'){e.respondWith(networkFirst(r,'./index.html'));return}if(u.pathname.endsWith('/diet-app.js')||u.pathname.endsWith('/diet.css')||u.pathname.endsWith('/manifest.webmanifest')||u.pathname.endsWith('/.well-known/thiepn-app.json')){e.respondWith(networkFirst(r));return}e.respondWith(caches.match(r).then(x=>x||fetch(r).then(res=>{if(res?.ok)caches.open(CACHE).then(c=>c.put(r,res.clone()));return res})))})\n`;
fs.writeFileSync('sw.js',sw);

const manifestPath='.well-known/thiepn-app.json';
const manifest=JSON.parse(fs.readFileSync(manifestPath,'utf8'));
manifest.release='V6.7';
manifest.webRelease=release;
manifest.productionBundle='diet-app.js';
manifest.productionStyles='diet.css';
manifest.runtimeMode='consolidated-release-candidate';
fs.writeFileSync(manifestPath,JSON.stringify(manifest,null,2)+'\n');

console.log(`Built Diet Copilot ${release}`);
console.log(`JS fragments: ${jsSources.length}; CSS fragments: ${cssSources.length}`);
console.log(`Production JS: ${Buffer.byteLength(js)} bytes; CSS: ${Buffer.byteLength(css)} bytes`);
